name:  make-ci-atmega32u4

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# on: push    # Default will running for every branch.
    
jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: keyboards/kb
          
    steps:
    - uses: actions/checkout@v3
    - name: Install avr-gcc dfu-programmer
      run: sudo apt update && sudo apt install gcc-avr dfu-programmer avr-libc -y
    - name: make
      run: make
    
    - uses: actions/upload-artifact@v1
      with:
        name: keyboard_hex_file
        path: kb_default.hex

